In [1]:
import pandas as pd
import requests
import os

# Descomprimir archivos

## Zip

In [2]:
# Importar zipfile
from zipfile import ZipFile

# Path a archivo zip
file = '../data/sales.zip'

# Leer archivo zip
with ZipFile(file, 'r') as objetoZip:
   # Extraer todo el contenido en la carpeta
   objetoZip.extractall("../data/")

## Tar Gz

In [3]:
# Importar archivo tar
import tarfile

# Abrir archivo tar.gz tgz
objetoTar = tarfile.open("../data/globos.tar.gz", "r:gz")
# Extraer todo el contenido en la carpeta
objetoTar.extractall("../data/")
# Cerrar lectura
objetoTar.close()

# Archivos de texto plano

## CSV

In [5]:
# Leer csv y convertirlo a panda frame
df = pd.read_csv('../data/class-grades.csv')
df

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
2        8       83.70     83.17    30.00     63.15  48.89
3        7       81.22     96.06    49.38    105.93  80.56
4        8       91.32     93.64    95.00    107.41  73.89
..     ...         ...       ...      ...       ...    ...
94       8       96.73    103.71    45.00     93.52  61.94
95       7       85.34     80.54    41.25     93.70  39.72
96       8       89.94    102.77    87.50     90.74  87.78
97       7       95.60     76.13    66.25     99.81  85.56
98       8       63.40     97.37    73.12     72.78  77.22

[99 rows x 6 columns]

In [5]:
# Especificar delimitador de columnas
df = pd.read_csv(r'../data/adult.data', delimiter = ",")
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [7]:
# Especificar que la primer columna no es la cabecera de la tabla
df = pd.read_csv('../data/agosto18.txt', delimiter = "\t", header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,01/08/18,0:30,29.6,29.8,29.6,30,10.1,1.3,S,2.41,...,0.234,31.6,25,9.1,29.9,0.00,685,2,100.0,30
1,01/08/18,1:00,29.4,29.6,29.2,30,10.0,0.4,S,0.80,...,0.230,31.6,25,9.1,29.9,0.10,685,2,100.0,30
2,01/08/18,1:30,30.8,30.8,29.4,26,9.1,0.9,S,1.61,...,0.260,31.4,25,9.0,29.8,0.00,685,2,100.0,30
3,01/08/18,2:00,30.8,31.0,30.8,25,8.5,1.8,S,3.22,...,0.259,31.4,25,9.0,29.8,0.13,682,2,100.0,30
4,01/08/18,2:30,30.7,30.8,30.7,25,8.4,1.8,S,3.22,...,0.257,31.4,25,9.0,29.8,0.00,685,2,100.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,31/08/18,22:00,32.6,33.6,32.6,25,10.0,0.0,NNW,0.00,...,0.297,34.4,27,12.7,33.9,0.03,686,2,100.0,30
1484,31/08/18,22:30,30.8,32.6,30.7,26,9.1,1.3,NE,2.41,...,0.260,34.4,27,12.7,33.9,0.00,686,2,100.0,30
1485,31/08/18,23:00,30.7,30.8,30.4,32,12.1,1.3,SSE,2.41,...,0.257,34.3,27,12.6,33.7,0.13,685,2,100.0,30
1486,31/08/18,23:30,30.6,30.7,30.6,33,12.5,1.3,SSE,2.41,...,0.255,34.2,27,12.5,33.6,0.00,686,2,100.0,30
1487,01/09/18,00:00,30.0,30.6,30.0,33,12.0,1.8,SSE,3.22,...,0.243,34.2,27,12.5,33.6,0.13,684,2,100.0,30

In [8]:
# Cargar cabecera a dataframe
df = pd.read_csv('../data/agosto18.txt', delimiter = "\t", header=None)
df.columns = ["Fecha","Hora","Columna 03", "Columna 04","Columna 05","Columna 06","Columna 07","Columna 08","Columna 09","Columna 10","Columna 11","Columna 12","Columna 13","Columna 14","Columna 15","Columna 16","Columna 17","Columna 18","Columna 19","Columna 20","Columna 21","Columna 22","Columna 23","Columna 24","Columna 25","Columna 26","Columna 27","Columna 28","Columna 29","Columna 30","Columna 31","Columna 32","Columna 33","Columna 34","Columna 35","Columna 36"]
df

,Fecha,Hora,Columna 03,Columna 04,Columna 05,Columna 06,Columna 07,Columna 08,Columna 09,Columna 10,...,Columna 27,Columna 28,Columna 29,Columna 30,Columna 31,Columna 32,Columna 33,Columna 34,Columna 35,Columna 36
0,01/08/18,0:30,29.6,29.8,29.6,30,10.1,1.3,S,2.41,...,0.234,31.6,25,9.1,29.9,0.00,685,2,100.0,30
1,01/08/18,1:00,29.4,29.6,29.2,30,10.0,0.4,S,0.80,...,0.230,31.6,25,9.1,29.9,0.10,685,2,100.0,30
2,01/08/18,1:30,30.8,30.8,29.4,26,9.1,0.9,S,1.61,...,0.260,31.4,25,9.0,29.8,0.00,685,2,100.0,30
3,01/08/18,2:00,30.8,31.0,30.8,25,8.5,1.8,S,3.22,...,0.259,31.4,25,9.0,29.8,0.13,682,2,100.0,30
4,01/08/18,2:30,30.7,30.8,30.7,25,8.4,1.8,S,3.22,...,0.257,31.4,25,9.0,29.8,0.00,685,2,100.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,31/08/18,22:00,32.6,33.6,32.6,25,10.0,0.0,NNW,0.00,...,0.297,34.4,27,12.7,33.9,0.03,686,2,100.0,30
1484,31/08/18,22:30,30.8,32.6,30.7,26,9.1,1.3,NE,2.41,...,0.260,34.4,27,12.7,33.9,0.00,686,2,100.0,30
1485,31/08/18,23:00,30.7,30.8,30.4,32,12.1,1.3,SSE,2.41,...,0.257,34.3,27,12.6,33.7,0.13,685,2,100.0,30
1486,31/08/18,23:30,30.6,30.7,30.6,33,12.5,1.3,SSE,2.41,...,0.255,34.2,27,12.5,33.6,0.00,686,2,100.0,30
1487,01/09/18,00:00,30.0,30.6,30.0,33,12.0,1.8,SSE,3.22,...,0.243,34.2,27,12.5,33.6,0.13,684,2,100.0,30

## JSON

In [6]:
# Importar librería de JSON
import json

# Leer archivo JSON
with open('../data/amazonia.json','r') as file:
    # Cargar contenido de JSON en diccionario
    data = json.load(file)


# Convertir JSON en dataframe
df = pd.DataFrame(data["items"])
df

,project,article,granularity,timestamp,access,agent,views
0,en.wikipedia,Amazon_rainforest,daily,2019050100,all-access,all-agents,2330
1,en.wikipedia,Amazon_rainforest,daily,2019050200,all-access,all-agents,2273
2,en.wikipedia,Amazon_rainforest,daily,2019050300,all-access,all-agents,2154
3,en.wikipedia,Amazon_rainforest,daily,2019050400,all-access,all-agents,1484
4,en.wikipedia,Amazon_rainforest,daily,2019050500,all-access,all-agents,1895
...,...,...,...,...,...,...,...
119,en.wikipedia,Amazon_rainforest,daily,2019082800,all-access,all-agents,41725
120,en.wikipedia,Amazon_rainforest,daily,2019082900,all-access,all-agents,27652
121,en.wikipedia,Amazon_rainforest,daily,2019083000,all-access,all-agents,20433
122,en.wikipedia,Amazon_rainforest,daily,2019083100,all-access,all-agents,16685
123,en.wikipedia,Amazon_rainforest,daily,2019090100,all-access,all-agents,13696

# Hojas de cálculo
## Excel

In [7]:
# Leer contenido de archivo Excel y convertirlo a dataframe
df = pd.read_excel(r'../data/vino.xls')
df

,row ID,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,Row0,6.7,0.24,0.30,10.2,0.07,44.0,179.0,0.99666,2.86,0.46,8.9,neutral,white
1,Row1,6.7,0.51,0.24,2.1,43.00,14.0,155.0,0.99040,3.22,0.60,13.0,neutral,white
2,Row2,6.9,0.18,0.38,6.5,39.00,20.0,110.0,0.99430,3.10,0.42,10.5,slightly dissatisfied,white
3,Row3,7.6,0.24,0.44,3.8,37.00,49.0,146.0,0.99110,3.06,0.37,11.6,neutral,white
4,Row4,7.0,0.46,0.20,16.7,46.00,50.0,184.0,0.99898,3.08,0.56,9.4,slightly dissatisfied,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,Row6492,5.8,555.00,0.26,4.5,53.00,17.0,126.0,0.99430,3.24,0.46,9.1,slightly dissatisfied,white
6493,Row6493,6.0,0.33,0.32,12.9,54.00,6.0,113.0,0.99572,3.30,0.56,11.5,moderately dissatisfied,red
6494,Row6494,6.7,0.86,0.07,2.0,0.10,20.0,57.0,0.99598,3.60,0.74,11.7,neutral,red
6495,Row6495,6.9,0.29,0.30,8.2,26.00,35.0,112.0,0.99144,3.00,0.37,12.3,neutral,white
6496,Row6496,6.4,0.26,0.43,12.6,33.00,64.0,230.0,0.99740,3.08,0.38,8.9,slightly dissatisfied,white

In [11]:
# Obtener archivo Excel
xl = pd.ExcelFile(r'../data/vino.xls')
# Obtener nombres de pestañas
xl.sheet_names

['vino', 'vino2']

In [12]:
# Leer contenido de una pestaña y convertirlo a dataframe
df = pd.read_excel(r'../data/vino.xls',sheet_name='vino2')
df

,row ID,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,Row0,6.7,0.24,0.30,10.2,0.07,44.0,179.0,0.99666,2.86,0.46,8.9,neutral,white
1,Row1,6.7,0.51,0.24,2.1,43.00,14.0,155.0,0.99040,3.22,0.60,13.0,neutral,white
2,Row2,6.9,0.18,0.38,6.5,39.00,20.0,110.0,0.99430,3.10,0.42,10.5,slightly dissatisfied,white
3,Row3,7.6,0.24,0.44,3.8,37.00,49.0,146.0,0.99110,3.06,0.37,11.6,neutral,white
4,Row4,7.0,0.46,0.20,16.7,46.00,50.0,184.0,0.99898,3.08,0.56,9.4,slightly dissatisfied,white
5,Row5,6.4,0.69,0.09,7.6,44.00,34.0,144.0,0.99480,3.26,0.38,10.1,neutral,white

## Libre Office Calc

In [8]:
# Leer contenido de una pestaña y convertirlo a dataframe
df = pd.read_excel(r'../data/vino.ods',sheet_name='vino')
df

,row ID,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,Row0,6.7,0.24,0.30,10.2,0.07,44.0,179.0,0.99666,2.86,0.46,8.9,neutral,white
1,Row1,6.7,0.51,0.24,2.1,43.00,14.0,155.0,0.99040,3.22,0.60,13.0,neutral,white
2,Row2,6.9,0.18,0.38,6.5,39.00,20.0,110.0,0.99430,3.10,0.42,10.5,slightly dissatisfied,white
3,Row3,7.6,0.24,0.44,3.8,37.00,49.0,146.0,0.99110,3.06,0.37,11.6,neutral,white
4,Row4,7.0,0.46,0.20,16.7,46.00,50.0,184.0,0.99898,3.08,0.56,9.4,slightly dissatisfied,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,Row6492,5.8,555.00,0.26,4.5,53.00,17.0,126.0,0.99430,3.24,0.46,9.1,slightly dissatisfied,white
6493,Row6493,6.0,0.33,0.32,12.9,54.00,6.0,113.0,0.99572,3.30,0.56,11.5,moderately dissatisfied,red
6494,Row6494,6.7,0.86,0.07,2.0,0.10,20.0,57.0,0.99598,3.60,0.74,11.7,neutral,red
6495,Row6495,6.9,0.29,0.30,8.2,26.00,35.0,112.0,0.99144,3.00,0.37,12.3,neutral,white
6496,Row6496,6.4,0.26,0.43,12.6,33.00,64.0,230.0,0.99740,3.08,0.38,8.9,slightly dissatisfied,white

# Base de datos

## SQLite

In [9]:
# Importar librería de SQLite
import sqlite3

# Abrir conexión con archivo
con=sqlite3.connect('../data/course.db')
# Crear objetuco cursor
cur = con.cursor()
# Ejecutar consulta
rs = cur.execute('select * from professor')
# Guardar resultados de la consulta en un dataframe
df = pd.DataFrame(rs.fetchall())
# Cerrar conexión
con.commit()
df

   0      1         2                           3
0  1  Marta  Gonzales  1992-03-02 00:00:00.000000
1  2  Pedro  Gonzales  1984-04-02 00:00:00.000000

## Mysql

In [15]:
# Importar conector mysql
import mysql.connector as connection
# Crear conexión a la db
db = connection.connect(host="localhost", database = 'Prueba',user="root", passwd="12345",use_pure=True)
# Consulta
query = "SELECT * from Profesores;"
# Realizar consulta y convertir el resultado en dataframe
df = pd.read_sql(query,db)
# Cerrar conexión
db.close()
df

/home/garenas/jupy/jup_notebook/lib/python3.10/site-packages/mysql/connector/abstracts.py:130: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if group is 'connector_python':
/home/garenas/jupy/jup_notebook/lib/python3.10/site-packages/mysql/connector/abstracts.py:130: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if group is 'connector_python':

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (111 Connection refused)

## PostgreSQL

In [10]:
# Importar conector postgreSQL
import psycopg2

try:
    credenciales = {
        "dbname": "bd1",
        "user": "postgres",
        "password": "basesita",
        "host": "127.0.0.1",
        "port": 5432
    }
    conexion = psycopg2.connect(**credenciales)

except psycopg2.Error as e:
    print("Ocurrió un error al conectar a PostgreSQL: ", e)

# Crear conexión a la db

# Consulta
#query = "SELECT * from Profesores;"
# Realizar consulta y convertir el resultado en dataframe
#df = pd.read_sql(query,db)
# Cerrar conexión
#db.close()
#df

# Creamos el cursor con el objeto conexion
#cur = conexion.cursor()

# Ejecutamos una consulta
cur.execute( "SELECT * FROM articulos" )

# Recorremos los resultados y los mostramos
for codigo,descripcion,precio in cur.fetchall() :
    print (codigo,descripcion,precio)

# Cerramos la conexión
conexion.close()

# Crear objetuco cursor
#cur = conexion.cursor()
# Ejecutar consulta
#rs = cur.execute('select * from articulos')
# Guardar resultados de la consulta en un dataframe
#df = pd.read_sql(rs,conexion)

#df = pd.DataFrame(rs.fetchall())
# Cerrar conexión
#conexion.close()
#df

Ocurrió un error al conectar a PostgreSQL:  connection to server at "127.0.0.1", port 5432 failed: FATAL:  la autentificación password falló para el usuario «postgres»
connection to server at "127.0.0.1", port 5432 failed: FATAL:  la autentificación password falló para el usuario «postgres»

OperationalError: no such table: articulos

# Web Scrapping

In [6]:
#import requests
##url = 'https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses'
#url = "https://www.worldometers.info/world-population/population-by-country/"

##Leer elementos table de html y convertirlos a dataframe
#tables = pd.read_html(url)
#df_poblacion = tablas[0]
##tables[1]
#print(df_poblacion.head())

import requests

url = "https://ejemplo.com/lander"
response = requests.get(url)
if response.status_code == 200:
    html = response.text
else:
    print("Error al acceder a la página")

In [7]:
import requests

# Obtener datos del usuario
user_url = "https://api.github.com/users/torvalds"
user_response = requests.get(user_url)
user_data = user_response.json()

# Obtener repositorios
repos_url = "https://api.github.com/users/torvalds/repos?per_page=5"
repos_response = requests.get(repos_url)
repos_data = repos_response.json()

# Mostrar resultados
print(f"Nombre: {user_data['name']}")
for repo in repos_data:
    print(f"Repositorio: {repo['name']}")

Nombre: Linus Torvalds
Repositorio: 1590A
Repositorio: GuitarPedal
Repositorio: libdc-for-dirk
Repositorio: libgit2
Repositorio: linux

In [10]:
#import requests
#import html5lib
#url = 'https://www.inpres.gob.ar/desktop/'

#Leer elementos table de html y convertirlos a dataframe
#tables = pd.read_html(url, header=0, index_col=0)
#tables = pd.read_html(url,header=0, index_col=0,encoding='ISO-8859-1')

#tables[6]

In [13]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, 'html.parser')
# Ejemplo: Extraer todos los títulos <h1>
titulos = soup.find_all('h1')
for titulo in titulos:
    print(titulo.text)

# Archivos remotos
## Descargar archivo

In [31]:
import requests
#URL
url = "https://cdn.buenosaires.gob.ar/datosabiertos/datasets/polideportivos/polideportivos.csv"
#Obtener URL
respuesta = requests.get(url)
#Obtener contenido de la respuesta
contenido = respuesta.content
#Abrir archivo para escritura
archivo = open('polideportivos.csv', 'wb')
#Escribir el contenido
archivo.write(contenido)
#Cerrar archivo
archivo.close()

## Leer remotamente

In [32]:
import pandas as pd
# Leer csv y convertirlo a panda frame
df = pd.read_csv(url)
df

,long,lat,id,nom_polid,calle,nro,telefono,domicilio,barrio,comuna,hor_atenc,valor_ent,codigo_postal,codigo_postal_argentino
0,-58.474297,-34.646008,1,AVELLANEDA,LACARRA,1257,4671-5932,1257 LACARRA,PARQUE AVELLANEDA,9,Todos los días de 8 a 20 horas.,Gratuito,1407.0,C1407JQY
1,-58.444741,-34.633075,2,CHACABUCO,PERON EVA,1410,4921-5776,1410 PERON EVA,PARQUE CHACABUCO,7,Todos los días de 8 a 20 horas.,Gratuito,1406.0,C1406HMP
2,-58.444674,-34.579459,3,COLEGIALES,CONDE,235,4555-7074,235 CONDE,COLEGIALES,13,Todos los días de 8 a 20 horas.,Gratuito,1426.0,C1426AYE
3,-58.476772,-34.591636,4,COSTA RICA,DE LOS CONSTITUYENTES & CHORROARIN,0,4521-8063,DE LOS CONSTITUYENTES & CHORROARIN,AGRONOMIA,15,Todos los días de 8 a 20 horas.,Gratuito,NaN,NaN
4,-58.376413,-34.638142,5,DON PEPE,HORNOS Gral. & BRANDSEN,0,4302-1618,HORNOS Gral. & BRANDSEN,BARRACAS,4,Todos los días de 8 a 20 horas.,Gratuito,NaN,NaN
5,-58.496045,-34.667435,6,DORREGO,DE LA TORRE LISANDRO & MONTE,0,4687-6823,DE LA TORRE LISANDRO & MONTE,MATADEROS,9,Todos los días de 8 a 20 horas.,Gratuito,NaN,NaN
6,-58.408577,-34.626085,7,MARTIN FIERRO,ORURO,1300,4941-2054,1300 ORURO,SAN CRISTOBAL,3,Todos los días de 8 a 20 horas.,Gratuito,1243.0,C1243ADB
7,-58.513758,-34.594424,8,ONEGA,MISTRAL GABRIELA,3819,4504-2711,3819 MISTRAL GABRIELA,VILLA DEVOTO,11,Todos los días de 8 a 20 horas.,Gratuito,1419.0,C1419GGI
8,-58.408894,-34.639098,9,PATRICIOS,PEPIRI,135,4911-4642,135 PEPIRI,PARQUE PATRICIOS,4,Todos los días de 8 a 20 horas.,Gratuito,1437.0,C1437EIC
9,-58.491151,-34.622347,10,POMAR,MERCEDES,1300,4568-0184,1300 MERCEDES,FLORESTA,10,Todos los días de 8 a 20 horas.,Gratuito,1407.0,C1407AHX
10,-58.513153,-34.646194,11,SANTOJANNI,PATRON,6222,4641-2462,6222 PATRON,LINIERS,9,Todos los días de 8 a 20 horas.,Gratuito,1408.0,C1408FAT
11,-58.389432,-34.649279,12,PEREYRA,VELEZ SARSFIELD,1271,4301-3700,1271 VELEZ SARSFIELD,BARRACAS,4,Todos los días de 8 a 20 horas.,Gratuito,1285.0,C1285AAB
12,-58.401799,-34.572699,13,MANUEL BELGRANO (ex KDT),COSTANERA AV & SALGUERO,0,4807-7700,COSTANERA AV & SALGUERO,PALERMO,14,"Lunes a viernes de 8 a 22hs. Sábados, Domingos...",Bono Contribución,NaN,NaN
13,-58.441525,-34.668011,14,JULIO A. ROCA,ROCA CNEL.,3490,3706-4954,3490 ROCA CNEL.,VILLA SOLDATI,8,Martes a Domingo de 9 a 19 horas.,Bono Contribución,1437.0,C1437KAN
14,-58.498510,-34.553102,15,SARMIENTO,BALBIN RICARDO DR. & PAZ GRAL AV,4750,4547-0882,4750 BALBIN RICARDO DR. & PAZ GRAL,SAAVEDRA,12,Todos los días de 8:30 a 18 horas.,"Bono Contribución-sábados,domingos y feriados",1430.0,C1430ABS
15,-58.434530,-34.558441,16,CAMPO DE GOLF,TORNQUINST,6397,4772-7261/7576,6397 TORNQUINST,PALERMO,14,Martes a Domingo de 9 a 18 horas. / 4777-4621 ...,Gratuito,NaN,NaN

# API  <a href="https://github.com/public-apis/public-apis">Lista de API de acceso público</a>

In [26]:
#import requests
#headers = {'Accept': 'application/json'}
#r = requests.get('https://reqbin.com/echo/get/json', headers=headers)
#print(f"Response: {r.json()}")

import requests

# The API endpoint
url = "https://jsonplaceholder.typicode.com/posts/1"
#url = "https://reqbin.com/echo/get/json"

# A GET request to the API
response = requests.get(url)

# Print the response
print(response.json())

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [27]:
import requests

# The API endpoint
url = "https://jsonplaceholder.typicode.com/posts"

# Data to be sent
data = {
    "userID": 1,
    "title": "Making a POST request",
    "body": "This is the data we created."
}

# A POST request to the API
response = requests.post(url, json=data)

# Print the response
print(response.json())

{'userID': 1, 'title': 'Making a POST request', 'body': 'This is the data we created.', 'id': 101}

In [17]:
# Realizar request a la API
import json
r = requests.get('https://dog-facts-api.herokuapp.com/api/v1/resources/dogs/all')
# r = requests.get('https://www.dogfactsapi.ducnguyen.dev/api/v1/facts/all')
# Convertir JSON a diccionario
data = r.json()

print(r)

# Convertir diccionario a dataframe
#df = pd.DataFrame(data)
#df

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [28]:
# Realizar request a la API
r = requests.get('https://palabras-aleatorias-public-api.herokuapp.com/palabras-aleatorias?_page=1&_size=5')
# Convertir JSON a diccionario
data = r.json()

# Convertir diccionario a dataframe
df = pd.DataFrame(data["body"])
df

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [7]:
# Realizar request a la API
r = requests.get('https://dog-facts-api.herokuapp.com/api/v1/resources/dogs/all')
# Convertir JSON a diccionario
data = r.json()


# Convertir diccionario a dataframe
df = pd.DataFrame(data)
df

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [29]:
import requests as req

api = 'some api'
header = {
    'Apikey': 'some token',
    'Content-Type': 'application/json'
}

payload = {
    "title": "TItle",
    "description": "<p>DEscription</p>",
    "column_id": 12345,
    "lane_id": 1234
}

URL = api + '/cards'

card_id = 0

def test_get_card():
    x = req.get(
        URL,
        headers=header,
        params={'cards_id': 123456}
    )

    assert x.status_code == 200

def test_create_card():
    x = req.post(
        URL,
        headers=header,
        data=payload
    ).json()

    print(x)

    assert x.status_code == 200