# TP2

## Valores faltantes

# Ejercicio 1

- Leer y obtener el siguiente dataset sobre <a href="https://archive.ics.uci.edu/ml/datasets/Sponge">esponjas</a>
- Analizar la naturaleza y distribución de los datos faltantes
- Selecccionar e implementar el mejor método para tratar los datos faltantes
- Justificar la elección

Primer paso- analizar el dataset

In [1]:
import pandas as pd
import requests
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# Leer csv
df = pd.read_csv('../data/sponge.data')

df

,AAPTOS_AAPTOS,1_CAPA,SIN_CAPA_INTERNA_DEL_CORTEX,SI,NO,NO.1,NO.2,3,NO.3,SIN_TILOSTILOS_ADICIONALES,...,MASIVO_IRREGULAR,0,NO.12,OTROS,RUGOSA,RADIAL,NO.13,NO.14,NO.15,DURO
0,ALECTONA_MILLARI,SIN_CORTEX,SIN_CAPA_INTERNA_DEL_CORTEX,NO,SIN_CORTEX,SIN_CORTEX,SIN_CORTEX,0,NO,SIN_TILOSTILOS_ADICIONALES,...,INCRUSTANTE,0,NO,?,LISA,CONFUSA,NO,SI,NO,DURO
1,CLIONA_CARTERI,SIN_CORTEX,SIN_CAPA_INTERNA_DEL_CORTEX,NO,SIN_CORTEX,SIN_CORTEX,SIN_CORTEX,0,NO,SIN_TILOSTILOS_ADICIONALES,...,INCRUSTANTE,1,SI,OTROS,LISA,CONFUSA,NO,SI,NO,DURO
2,CLIONA_CELATA,SIN_CORTEX,SIN_CAPA_INTERNA_DEL_CORTEX,NO,SIN_CORTEX,SIN_CORTEX,SIN_CORTEX,0,NO,SIN_TILOSTILOS_ADICIONALES,...,MASIVO_IRREGULAR,3,SI,OTROS,LISA,CONFUSA,NO,SI,NO,DURO
3,CLIONA_LABYRINTHICA,SIN_CORTEX,SIN_CAPA_INTERNA_DEL_CORTEX,NO,SIN_CORTEX,SIN_CORTEX,SIN_CORTEX,0,NO,SIN_TILOSTILOS_ADICIONALES,...,INCRUSTANTE,0,NO,OTROS,LISA,CONFUSA,NO,SI,NO,DURO
4,CLIONA_SCHMIDTI,SIN_CORTEX,SIN_CAPA_INTERNA_DEL_CORTEX,NO,SIN_CORTEX,SIN_CORTEX,SIN_CORTEX,0,NO,SIN_TILOSTILOS_ADICIONALES,...,INCRUSTANTE,1,SI,OTROS,LISA,CONFUSA,NO,SI,NO,DURO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,TRICHOSTEMA_HEMISPHAERICUM,1_CAPA,SIN_CAPA_INTERNA_DEL_CORTEX,SI,NO,NO,NO,4,NO,INTERMEDIARIOS_Y_ECTOSOMICOS,...,HEMISFERICA,2,SI,OTROS,FRANJA_BASAL_DE_ESPICULAS_EN_FLECO,RADIAL,NO,NO,NO,BLANDO
71,TRICHOSTEMA_SARSI,1_CAPA,SIN_CAPA_INTERNA_DEL_CORTEX,SI,NO,NO,NO,3,NO,INTERMEDIARIOS_Y_ECTOSOMICOS,...,DE_CONO_INVERTIDO,2,SI,?,FRANJA_BASAL_DE_ESPICULAS_EN_FLECO,RADIAL,NO,NO,NO,BLANDO
72,TYLEXOCLADUS_JOUBINI,1_CAPA,SIN_CAPA_INTERNA_DEL_CORTEX,SI,NO,NO,NO,3,NO,ECTOSOMICOS_EN_RAMILLETES,...,DE_REVESTIMIENTO,0,NO,?,HISPIDEZ_MAYOR_HACIA_LA_BASE,RADIAL,NO,NO,NO,DURO
73,WEBERELLA_BURSA,2_CAPAS,TANGENCIAL,SI,SI,NO,NO,3,NO,INTERMEDIARIOS_Y_ECTOSOMICOS,...,GLOBULOSA,2,SI,OTROS,ATERCIOPELADA,RADIAL_EN_PERIFERIA,NO,NO,NO,DURO
74,WEBERELLA_VERRUCOSA,2_CAPAS,TANGENCIAL,SI,NO,NO,NO,2,NO,SIN_TILOSTILOS_ADICIONALES,...,GLOBULOSA,2,SI,OTROS,ATERCIOPELADA,RADIAL_EN_PERIFERIA,NO,NO,NO,DURO

# Ver dimensiones

In [2]:
# Ver tamaño del datase
df.shape

(75, 46)

# Ver tipo de atributos¶

In [3]:
# Ver tipo de atributos
df.dtypes

AAPTOS_AAPTOS                        object
1_CAPA                               object
SIN_CAPA_INTERNA_DEL_CORTEX          object
SI                                   object
NO                                   object
NO.1                                 object
NO.2                                 object
3                                     int64
NO.3                                 object
SIN_TILOSTILOS_ADICIONALES           object
1_TIPO                               object
NO.4                                 object
NO.5                                 object
NO.6                                 object
NO.7                                 object
SI.1                                 object
NO.8                                 object
NO.9                                 object
SIN_ESPICULA_PRINCIPAL_ESTILO        object
SIN_ESPICULA_PRINCIPAL_TILOSTILO_    object
SIN_TILOSTILOS                       object
EMPALIZADA                           object
SUBESFERICA_ALARGADA_OVOIDE          object
RECTA_FUSIFORME                      object
ESTILO                               object
SIN_EXOSTILOS                        object
SIN_MEGASCLERA_INTERMEDIARIA         object
SIN_MEGASCLERA_INTERMEDIARIA.1       object
3.1                                   int64
NO.10                                object
SIN_MICROSCLERAS                     object
NO.11                                object
SIN_ESFERASTER                       object
SIN_ASTER                            object
SIN_DIPLASTERES                      object
SIN_ESFERASTER.1                     object
MASIVO_IRREGULAR                     object
0                                     int64
NO.12                                object
OTROS                                object
RUGOSA                               object
RADIAL                               object
NO.13                                object
NO.14                                object
NO.15                                object
DURO                                 object
dtype: object

# Ver información general

In [4]:
# Ver información general
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 46 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   AAPTOS_AAPTOS                      75 non-null     object
 1   1_CAPA                             75 non-null     object
 2   SIN_CAPA_INTERNA_DEL_CORTEX        75 non-null     object
 3   SI                                 75 non-null     object
 4   NO                                 75 non-null     object
 5   NO.1                               75 non-null     object
 6   NO.2                               75 non-null     object
 7   3                                  75 non-null     int64
 8   NO.3                               75 non-null     object
 9   SIN_TILOSTILOS_ADICIONALES         75 non-null     object
 10  1_TIPO                             75 non-null     object
 11  NO.4                               75 non-null     object
 12  NO.5                               75 non-null     object
 13  NO.6                               75 non-null     object
 14  NO.7                               75 non-null     object
 15  SI.1                               75 non-null     object
 16  NO.8                               75 non-null     object
 17  NO.9                               75 non-null     object
 18  SIN_ESPICULA_PRINCIPAL_ESTILO      75 non-null     object
 19  SIN_ESPICULA_PRINCIPAL_TILOSTILO_  75 non-null     object
 20  SIN_TILOSTILOS                     75 non-null     object
 21  EMPALIZADA                         75 non-null     object
 22  SUBESFERICA_ALARGADA_OVOIDE        75 non-null     object
 23  RECTA_FUSIFORME                    75 non-null     object
 24  ESTILO                             75 non-null     object
 25  SIN_EXOSTILOS                      75 non-null     object
 26  SIN_MEGASCLERA_INTERMEDIARIA       75 non-null     object
 27  SIN_MEGASCLERA_INTERMEDIARIA.1     75 non-null     object
 28  3.1                                75 non-null     int64
 29  NO.10                              75 non-null     object
 30  SIN_MICROSCLERAS                   75 non-null     object
 31  NO.11                              75 non-null     object
 32  SIN_ESFERASTER                     75 non-null     object
 33  SIN_ASTER                          75 non-null     object
 34  SIN_DIPLASTERES                    75 non-null     object
 35  SIN_ESFERASTER.1                   75 non-null     object
 36  MASIVO_IRREGULAR                   75 non-null     object
 37  0                                  75 non-null     int64
 38  NO.12                              75 non-null     object
 39  OTROS                              75 non-null     object
 40  RUGOSA                             75 non-null     object
 41  RADIAL                             75 non-null     object
 42  NO.13                              75 non-null     object
 43  NO.14                              75 non-null     object
 44  NO.15                              75 non-null     object
 45  DURO                               75 non-null     object
dtypes: int64(3), object(43)
memory usage: 27.1+ KB

# Ver datos faltantes

In [5]:
faltantes = []
for columna in df.columns:
    atributo = {}
    atributo["columna"] = columna
    # Obtener promedio de valores nulos para la columna
    atributo["porcentaje"] = np.mean(df[columna].isnull())*100
    # Obtener cantidad de valores nulos para la columna
    atributo["cantidad"] = np.sum(df[columna].isnull())
    faltantes.append(atributo)  

# Convertir lista de diccionarios en dataframe
faltantes_df = pd.DataFrame(faltantes)

faltantes_df

                              columna  porcentaje  cantidad
0                       AAPTOS_AAPTOS         0.0         0
1                              1_CAPA         0.0         0
2         SIN_CAPA_INTERNA_DEL_CORTEX         0.0         0
3                                  SI         0.0         0
4                                  NO         0.0         0
5                                NO.1         0.0         0
6                                NO.2         0.0         0
7                                   3         0.0         0
8                                NO.3         0.0         0
9          SIN_TILOSTILOS_ADICIONALES         0.0         0
10                             1_TIPO         0.0         0
11                               NO.4         0.0         0
12                               NO.5         0.0         0
13                               NO.6         0.0         0
14                               NO.7         0.0         0
15                               SI.1         0.0         0
16                               NO.8         0.0         0
17                               NO.9         0.0         0
18      SIN_ESPICULA_PRINCIPAL_ESTILO         0.0         0
19  SIN_ESPICULA_PRINCIPAL_TILOSTILO_         0.0         0
20                     SIN_TILOSTILOS         0.0         0
21                         EMPALIZADA         0.0         0
22        SUBESFERICA_ALARGADA_OVOIDE         0.0         0
23                    RECTA_FUSIFORME         0.0         0
24                             ESTILO         0.0         0
25                      SIN_EXOSTILOS         0.0         0
26       SIN_MEGASCLERA_INTERMEDIARIA         0.0         0
27     SIN_MEGASCLERA_INTERMEDIARIA.1         0.0         0
28                                3.1         0.0         0
29                              NO.10         0.0         0
30                   SIN_MICROSCLERAS         0.0         0
31                              NO.11         0.0         0
32                     SIN_ESFERASTER         0.0         0
33                          SIN_ASTER         0.0         0
34                    SIN_DIPLASTERES         0.0         0
35                   SIN_ESFERASTER.1         0.0         0
36                   MASIVO_IRREGULAR         0.0         0
37                                  0         0.0         0
38                              NO.12         0.0         0
39                              OTROS         0.0         0
40                             RUGOSA         0.0         0
41                             RADIAL         0.0         0
42                              NO.13         0.0         0
43                              NO.14         0.0         0
44                              NO.15         0.0         0
45                               DURO         0.0         0

# Ejercicio 2

- Leer y obtener el siguiente dataset sobre <a href="https://archive.ics.uci.edu/ml/datasets/Echocardiogram">ecocardiogramas</a>
- Analizar la naturaleza y distribución de los datos faltantes
- Selecccionar e implementar el mejor método para tratar los datos faltantes
- Justificar la elección